// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: internal/webhook/api/forward.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebhookForwardData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload string `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *WebhookForwardData) Reset() {
	*x = WebhookForwardData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_webhook_api_forward_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebhookForwardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookForwardData) ProtoMessage() {}

func (x *WebhookForwardData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_webhook_api_forward_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookForwardData.ProtoReflect.Descriptor instead.
func (*WebhookForwardData) Descriptor() ([]byte, []int) {
	return file_internal_webhook_api_forward_proto_rawDescGZIP(), []int{0}
}

func (x *WebhookForwardData) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type WebhookForwardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *WebhookForwardResponse) Reset() {
	*x = WebhookForwardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_webhook_api_forward_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebhookForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookForwardResponse) ProtoMessage() {}

func (x *WebhookForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_webhook_api_forward_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookForwardResponse.ProtoReflect.Descriptor instead.
func (*WebhookForwardResponse) Descriptor() ([]byte, []int) {
	return file_internal_webhook_api_forward_proto_rawDescGZIP(), []int{1}
}

func (x *WebhookForwardResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_webhook_api_forward_proto protoreflect.FileDescriptor

var file_internal_webhook_api_forward_proto_rawDesc = []byte{
	0x0a, 0x22, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x77, 0x65, 0x62, 0x68, 0x6f,
	0x6f, 0x6b, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x68, 0x61, 0x74, 0x22, 0x2e, 0x0a, 0x12, 0x57, 0x65,
	0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x2e, 0x0a, 0x16, 0x57, 0x65,
	0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x60, 0x0a, 0x15, 0x57, 0x65,
	0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x07, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x12, 0x18,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x46, 0x6f, 0x72,
	0x77, 0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x1c, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e,
	0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_webhook_api_forward_proto_rawDescOnce sync.Once
	file_internal_webhook_api_forward_proto_rawDescData = file_internal_webhook_api_forward_proto_rawDesc
)

func file_internal_webhook_api_forward_proto_rawDescGZIP() []byte {
	file_internal_webhook_api_forward_proto_rawDescOnce.Do(func() {
		file_internal_webhook_api_forward_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_webhook_api_forward_proto_rawDescData)
	})
	return file_internal_webhook_api_forward_proto_rawDescData
}

var file_internal_webhook_api_forward_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_webhook_api_forward_proto_goTypes = []interface{}{
	(*WebhookForwardData)(nil),     // 0: chat.WebhookForwardData
	(*WebhookForwardResponse)(nil), // 1: chat.WebhookForwardResponse
}
var file_internal_webhook_api_forward_proto_depIdxs = []int32{
	0, // 0: chat.WebhookForwardService.Forward:input_type -> chat.WebhookForwardData
	1, // 1: chat.WebhookForwardService.Forward:output_type -> chat.WebhookForwardResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_webhook_api_forward_proto_init() }
func file_internal_webhook_api_forward_proto_init() {
	if File_internal_webhook_api_forward_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_webhook_api_forward_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebhookForwardData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_webhook_api_forward_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebhookForwardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_webhook_api_forward_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_webhook_api_forward_proto_goTypes,
		DependencyIndexes: file_internal_webhook_api_forward_proto_depIdxs,
		MessageInfos:      file_internal_webhook_api_forward_proto_msgTypes,
	}.Build()
	File_internal_webhook_api_forward_proto = out.File
	file_internal_webhook_api_forward_proto_rawDesc = nil
	file_internal_webhook_api_forward_proto_goTypes = nil
	file_internal_webhook_api_forward_proto_depIdxs = nil
}
